services:
  postgres:
    image: postgres:16-alpine
    container_name: run-the-world-db
    environment:
      POSTGRES_USER: runtheworld
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: runtheworld
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U runtheworld"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
